version: '3.5'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '12345678'
      PGDATA: /data/postgres

  pgadmin:
    build: ./
    environment:
      PGADMIN_DISABLE_POSTFIX: 'true'
      PGADMIN_DEFAULT_EMAIL: root@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: '12345678'
      DEFAULT_SERVER_HOST: db
      DEFAULT_SERVER_PORT: '5432'
      DEFAULT_SERVER_USER: postgres
      DEFAULT_SERVER_PASSWORD: '12345678'
      DEFAULT_MAINTENANCE_DB: postgres
    ports:
      - "7000:80"
